server:
  port: 5004

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:5020
          predicates:
            - Path=/auth/**
          # no rewrite needed if auth-service already uses /auth/**
          # filters: []

        - id: patient-service-route
          uri: http://patient-service:5001
          predicates:
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/patients(?<remaining>/?.*),/patients${remaining}
            - JwtValidation

        # ? expose auth openapi through gateway at /v3/api-docs/auth
        - id: openapi-auth
          uri: http://auth-service:5020
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - SetPath=/v3/api-docs

        # ? expose patient openapi through gateway at /v3/api-docs/patient
        - id: openapi-patient
          uri: http://patient-service:5001
          predicates:
            - Path=/v3/api-docs/patient
          filters:
            - SetPath=/v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: patient-service
        url: /v3/api-docs/patient
